CREATE TABLE IF NOT EXISTS candidate_discovery_events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    candidate_id BIGINT NOT NULL,
    google_place_id VARCHAR(255) NOT NULL,
    search_task_id BIGINT,
    source_location_id BIGINT,
    source_location_type TEXT,
    source_location_name TEXT,
    state_name VARCHAR(255),
    district_name VARCHAR(255),
    keyword VARCHAR(255),
    search_query TEXT NOT NULL,
    search_level VARCHAR(255),
    result_position INTEGER CHECK (
        result_position IS NULL OR result_position >= 1
    ),
    discovered_name TEXT NOT NULL,
    discovered_address TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    google_maps_uri TEXT,
    observed_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    UNIQUE KEY idx_candidate_discovery_events_task_place (search_task_id, google_place_id),
    KEY idx_candidate_discovery_events_candidate (candidate_id, observed_at),
    KEY idx_candidate_discovery_events_place (google_place_id),
    KEY idx_candidate_discovery_events_location (source_location_id, observed_at),
    KEY idx_candidate_discovery_events_level (search_level, observed_at),
    FOREIGN KEY (candidate_id) REFERENCES temple_candidates(id) ON DELETE CASCADE,
    FOREIGN KEY (search_task_id) REFERENCES temple_search_tasks(id) ON DELETE SET NULL,
    FOREIGN KEY (source_location_id) REFERENCES india_locations(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
