from __future__ import annotations

import argparse
import csv
from pathlib import Path

import _bootstrap  # noqa: F401
from shiva_discovery.db import connect
from shiva_discovery.district_alignment import alignment_row, build_district_alignment
from shiva_discovery.normalization import normalize_name


FIELDNAMES = [
    "match_status",
    "match_method",
    "match_score",
    "review_reason",
    "db_id",
    "db_state_name",
    "db_district_name",
    "db_state_lgd_code",
    "db_district_lgd_code",
    "db_source",
    "lgd_state_name",
    "lgd_district_name",
    "lgd_state_lgd_code",
    "lgd_district_lgd_code",
    "lgd_source",
]


def _read_lgd_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))


def _fetch_db_districts(conn) -> list[dict[str, object]]:
    with conn.cursor() as cursor:
        cursor.execute(
            """
            SELECT
                id,
                name,
                state_name,
                district_name,
                state_lgd_code,
                district_lgd_code,
                source,
                full_path,
                search_priority,
                is_active
            FROM india_locations
            WHERE location_type = 'district'
            ORDER BY state_name, district_name, name, id;
            """
        )
        columns = [description[0] for description in cursor.description]
        return [dict(zip(columns, row)) for row in cursor.fetchall()]


def _write_alignment(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDNAMES)
        writer.writeheader()
        writer.writerows(rows)


def _apply_auto_matches(conn, alignment_rows: list[dict[str, object]]) -> int:
    applied = 0
    with conn.cursor() as cursor:
        for row in alignment_rows:
            if row["match_status"] != "auto" or not row["db_id"]:
                continue
            full_path = f"{row['lgd_state_name']} > {row['lgd_district_name']}"
            cursor.execute(
                """
                UPDATE india_locations
                SET
                    name = %s,
                    normalized_name = %s,
                    state_name = %s,
                    district_name = %s,
                    state_lgd_code = %s,
                    district_lgd_code = %s,
                    source = 'lgd',
                    full_path = %s,
                    updated_at = NOW()
                WHERE id = %s
                  AND location_type = 'district';
                """,
                (
                    row["lgd_district_name"],
                    normalize_name(row["lgd_district_name"]),
                    row["lgd_state_name"],
                    row["lgd_district_name"],
                    row["lgd_state_lgd_code"],
                    row["lgd_district_lgd_code"],
                    full_path,
                    int(row["db_id"]),
                ),
            )
            applied += cursor.rowcount
    return applied


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Align existing DB district rows to official LGD district names and codes."
    )
    parser.add_argument(
        "--lgd-districts",
        default="data/prepared_locations_lgd_districts.csv",
        help="Prepared LGD district CSV generated by prepare_location_sources.py.",
    )
    parser.add_argument(
        "--output",
        default="reports/location_verification/district_alignment_review.csv",
        help="Review CSV output path.",
    )
    parser.add_argument(
        "--apply-auto",
        action="store_true",
        help="Update DB rows for auto-safe matches only. Review/missing/db-only rows are not changed.",
    )
    args = parser.parse_args()

    lgd_rows = _read_lgd_rows(Path(args.lgd_districts))
    with connect() as conn:
        db_rows = _fetch_db_districts(conn)
        matches = build_district_alignment(lgd_rows=lgd_rows, db_rows=db_rows)
        rows = [alignment_row(match) for match in matches]
        _write_alignment(Path(args.output), rows)

        counts: dict[str, int] = {}
        for row in rows:
            counts[str(row["match_status"])] = counts.get(str(row["match_status"]), 0) + 1

        print(f"LGD district rows: {len(lgd_rows)}")
        print(f"DB district rows: {len(db_rows)}")
        for status in ("auto", "review", "missing_in_db", "db_only"):
            print(f"{status}: {counts.get(status, 0)}")
        print(f"Wrote {args.output}")

        if args.apply_auto:
            with conn.transaction():
                applied = _apply_auto_matches(conn, rows)
            print(f"Applied {applied} auto district alignments.")
        else:
            print("Dry run only. Pass --apply-auto to update auto-safe DB district rows.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
